### ISSUE TITLE
TableView doesn't allow for unicode chars.

### ISSUE THREAD

**Issue by viktor-rick** [viktor-platform/viktor_table_view#3]
TableView doesn't have char encoding specified; so it will use ANSI in stead of UTF-8. This makes unicode chars not work for the TableView.

`<head>`
`    <title></title>`
`    <meta charset="UTF-8">` <- new line
`    <meta name ="viewport" ...........>`

**Comment by viktor-rick** [comment]
@svandermeer 

Could you specifiy the encoding. This issue will also be made at the frontend side of Viktor, but I believe its good practice to specify it.

**Comment by svandermeer** [comment]
@viktor-rick great suggestion. I'll implement it now. Could you next time please make a PR with the new suggestion?
